# DeepSource configuration file
version = 1
exclude_patterns = ["node_modules", "bower_components", "out", "bin", "build", "dist"]
test_patterns = ["**/__tests__/**", "**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js"]

[[analyzers]]
  name = "javascript"
  enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "es6"
  ecma_version = 2021