services:
  app:
    build: .
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      SECRET_JWT_KEY: ${SECRET_JWT_KEY}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - db
      - mongo

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${EXTERNAL_PGPORT}:${PGPORT}"

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: