$kind: http-request
name: Update Task
method: PUT
url: '{{baseUrl}}/api/v1/tasks/1'
order: 4000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "name": "Updated task",
      "status": "IN_PROGRESS",
      "userStoryId": 1
    }
