$kind: http-request
name: Create Task
method: POST
url: '{{baseUrl}}/api/v1/tasks'
order: 2000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "name": "My Task",
      "projectId": 1
    }
